using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using NPOI.SS.UserModel;


namespace LPTCTool
{
    class Program
    {
        private static string s_excelPath = "D:\\StudyData\\VSProjects\\SmapleServer\\Resouces\\LPTC.xlsx";
        private static string s_outPath = "D:\\StudyData\\VSProjects\\SmapleServer\\Potocol\\AutoGenerated";
        static void Main(string[] args)
        {
            Console.WriteLine("按下Enter 生成脚本");
            while(Console.ReadKey().Key != ConsoleKey.Enter)
            {
                Console.WriteLine("按下Enter 生成脚本");
            }
            IWorkbook workbook = WorkbookFactory.Create(s_excelPath);
            ISheet sheet = workbook.GetSheetAt(0);//获取第一个工作薄
            for (int i = 0; i < sheet.LastRowNum + 1; i++)
            {
                var row = sheet.GetRow(i);
                LPTCCreator.ExcelRowToScripts(row, s_outPath);
            }
            LPTCCreator.CreateLPTCEnum(sheet, s_outPath);
            Console.WriteLine("生成完成!按任意键退出......");
            Console.ReadKey();
        }

        
    }
}
